language: c

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libsdl1.2-dev libpcap0.8-dev libcurl4-openssl-dev build-essential

install: true

script: cd ipvisualizer && ./configure && make && make test

